# Machine Learning Data Loaders - Conda Environment
# Create environment with: conda env create -f environment.yml
# Activate with: conda activate ml-loaders

name: ml-loaders
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - scikit-learn>=1.3.0
  - pip
  - pip:
    # LLM Feature Engineering (Optional - install only if using these modules)
    - anthropic>=0.40.0  # For LLMFeatureEngineer.py - Claude API client
    - ollama>=0.4.0      # For OllamaFeatureEngineer.py - Local LLM client
